#!/usr/bin/env bash
# Script that installs nginx on my web-01 server
#+ Nginx should be listening on port 80
#+ When querying Nginx at its root / with a GET request 
#+ (requesting a page) using curl, it must return a page that contains
#+ The string Hello World.

sudo apt-get -y update
sudo apt-get -y install nginx

sudo mkdir /var/www/html
sudo touch /var/www/html/index.html
sudo service nginx start
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
