#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+ Listens on port 80.
#+ Returns a page containing "Hello World!" when queried
#+ at the root with a curl GET request.
#+ Configures /redirect_me as a "301 Moved Permanently".
#+ Contains a custom HTTP header named X-Served-By.
#+ The value of the HTTP header is the hostname of the running server.

sudo apt update
sudo apt install -y nginx
sudo apt install -y sed
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i 's/server_name _;$/server_name _;\n\n\tadd_header X-Served-By $hostname;\n/' /etc/nginx/sites-enabled/default
sudo service nginx restart
