#!/usr/bin/env bash
#+ Bash Script that Installs and configure HAproxy on your lb-01 server
#+ Configure HAproxy so that it send traffic to web-01 and web-02
#+ Distribute requests using a roundrobin algorithm
#+ Make sure that HAproxy can be managed via an init script
#+ Make sure that your servers are configured with the right hostnames:
#+ [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get update
sudo apt-get install -y haproxy=2.6.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    maxconn 5000
    log /dev/log local0
    user haproxy
    group haproxy

defaults
    log	global
    mode http
    option httplog
    maxconn 2000
    timeout connect 10000
    timeout client 30000
    timeout server 30000

frontend tcreate.tech
    bind *:80
    option forwardfor
    default_backend web_servers

backend web_servers
    balance roundrobin
    default-server check maxconn 20
    server web-01 3.235.20.78:80 check
    server web-02 44.201.70.161:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
