#!/usr/bin/env bash
#+ Bash Script that Installs and configure HAproxy on your lb-01 server
#+ Configure HAproxy so that it send traffic to web-01 and web-02
#+ Distribute requests using a roundrobin algorithm
#+ Make sure that HAproxy can be managed via an init script
#+ Make sure that your servers are configured with the right hostnames:
#+ [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.

sudo apt update
sudo apt install -y haproxy

sudo touch /etc/haproxy/haproxy.cfg

sudo sh -c 'printf %s "frontend tcreate.tech
    bind *:80
    option forwardfor
    default_backend web_servers

backend web_servers
    balance roundrobin
    default-server check maxconn 20
    server 6879-web-01 3.235.20.78:80 check
    server 6879-web-02 44.201.70.161:80 check
" > /etc/haproxy/haproxy.cfg'

sudo service haproxy restart
