CHANGE MASTER TO
MASTER_HOST='3.235.20.78',
MASTER_USER='replica_user',
MASTER_PASSWORD='betty',
MASTER_LOG_FILE='mysql-bin.000001',
MASTER_LOG_POS=154;

START SLAVE;
SHOW SLAVE STATUS\G
-- STOP SLAVE;
