#!/usr/bin/env bash
# Script that
#+ Create the file /var/run/myscript.pid containing its PID
#+ Displays To infinity and beyond indefinitely
#+ Displays I hate the kill command on SIGTERM signal
#+ Displays Y U no love me? on SIGINT signal
#+ Deletes the file /var/run/myscript.pid and terminates on SIGQUIT or SIGTERM

terminator() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'terminator' SIGQUIT
done
