#!/usr/bin/env bash
# Script loops from 1 to 10
#+ Displays "bad luck" for 4th loop
#+ Displays "good luck" for 8th loop
#+ Displays "Best SCchool" for other iterations

i="0"

while [ $i -lt 10 ]
do
	if [ $i -eq "3" ]
	then
		echo "bad luck"
	elif [ $i -eq "7" ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
