#!/usr/bin/env bash
# Script that displays the content of the current directory
#+ In a list format
#+ Where only the part of the name after the first dash is displayed

for i in $(ls)
do
	echo "$i" | cut -d '-' -f2
done
