#!/usr/bin/env bash
# Configure ufw so that it blocks incoming traffic, except
# TCP ports 22, 80, and 443
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
